[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:pocketbase]
command=pocketbase serve --http=0.0.0.0:8090 --dir=/app/pb_data --migrationsDir=/app/pb_migrations --hooksDir=/app/pb_hooks
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nextjs]
command=node server.js
directory=/app
autostart=true
autorestart=true
environment=NODE_ENV="production",HOSTNAME="0.0.0.0",PORT="3000"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
